syntax = "proto3";

package ratelimiter;

// The RateLimiter Service declaration
service RateLimiter {
  // Validates and returns the rate limit status for a client key
  rpc CheckLimit (RateLimitRequest) returns (RateLimitResponse);
}

// Client request payload
message RateLimitRequest {
  string key = 1;
  int64 max_tokens = 2;
  double refill_rate = 3;
  string algorithm = 4;
}

// Server response payload
message RateLimitResponse {
  bool allowed = 1;
  int64 remaining_tokens = 2;
  int64 reset_time_seconds = 3;
}