# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protobuf/rate_limiter.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'protobuf/rate_limiter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bprotobuf/rate_limiter.proto\x12\x0bratelimiter\"[\n\x10RateLimitRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x12\n\nmax_tokens\x18\x02 \x01(\x03\x12\x13\n\x0brefill_rate\x18\x03 \x01(\x01\x12\x11\n\talgorithm\x18\x04 \x01(\t\"Z\n\x11RateLimitResponse\x12\x0f\n\x07\x61llowed\x18\x01 \x01(\x08\x12\x18\n\x10remaining_tokens\x18\x02 \x01(\x03\x12\x1a\n\x12reset_time_seconds\x18\x03 \x01(\x03\x32Z\n\x0bRateLimiter\x12K\n\nCheckLimit\x12\x1d.ratelimiter.RateLimitRequest\x1a\x1e.ratelimiter.RateLimitResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf.rate_limiter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RATELIMITREQUEST']._serialized_start=44
  _globals['_RATELIMITREQUEST']._serialized_end=135
  _globals['_RATELIMITRESPONSE']._serialized_start=137
  _globals['_RATELIMITRESPONSE']._serialized_end=227
  _globals['_RATELIMITER']._serialized_start=229
  _globals['_RATELIMITER']._serialized_end=319
# @@protoc_insertion_point(module_scope)
