# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protobuf import rate_limiter_pb2 as protobuf_dot_rate__limiter__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in protobuf/rate_limiter_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RateLimiterStub(object):
    """The RateLimiter Service declaration
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckLimit = channel.unary_unary(
                '/ratelimiter.RateLimiter/CheckLimit',
                request_serializer=protobuf_dot_rate__limiter__pb2.RateLimitRequest.SerializeToString,
                response_deserializer=protobuf_dot_rate__limiter__pb2.RateLimitResponse.FromString,
                _registered_method=True)


class RateLimiterServicer(object):
    """The RateLimiter Service declaration
    """

    def CheckLimit(self, request, context):
        """Validates and returns the rate limit status for a client key
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RateLimiterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckLimit': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckLimit,
                    request_deserializer=protobuf_dot_rate__limiter__pb2.RateLimitRequest.FromString,
                    response_serializer=protobuf_dot_rate__limiter__pb2.RateLimitResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ratelimiter.RateLimiter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ratelimiter.RateLimiter', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RateLimiter(object):
    """The RateLimiter Service declaration
    """

    @staticmethod
    def CheckLimit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ratelimiter.RateLimiter/CheckLimit',
            protobuf_dot_rate__limiter__pb2.RateLimitRequest.SerializeToString,
            protobuf_dot_rate__limiter__pb2.RateLimitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
